apiVersion: v2
name: directus
description: A Helm chart for deploying Directus Headless CMS to Kubernetes
type: application
version: 0.1.0


dependencies:
- name: postgresql
  version: "12.2.0"
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: "17.8.5"
  repository: "https://charts.bitnami.com/bitnami"
  condition: redis.enabled
