replicaCount: 1

# https://hub.docker.com/r/directus/directus/tags
image:
  repository: directus/directus
  pullPolicy: IfNotPresent
  tag: "9.23"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

resources: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8055

ingress:
  enabled: false

ingressroute:
  enabled: true
  hosts:
    - host: cms.pleiades.kolv.in
      path: /

directusEnvVars:
  - name: ADMIN_EMAIL
    value: "taylorcalvin07@gmail.com"
  - name: ADMIN_PASSWORD
    value: "d1r3ctu5"
  - name: KEY
    value: "6aeb8a0c-fdd5-4356-b5a8-c61fa83fc0ac"
  - name: SECRET
    value: "4c28b02f-6c4c-4e8d-a40f-fa5a25f3d691"
  - name: DB_CLIENT
    value: "postgres"
  - name: DB_HOST
    value: "10.19.1.212"
  - name: DB_PORT
    value: "5432"
  - name: DB_DATABASE
    value: "directus"
  - name: DB_USER
    value: "directus"
  - name: DB_PASSWORD 
    valueFrom:
      secretKeyRef:
        name: directus-postgresql
        key: password
  - name: CACHE_ENABLED
    value: "true"
  - name: CACHE_TTL
    value: "5m"
  - name: CACHE_STORE
    value: "redis"
  - name: CACHE_REDIS_HOST
    value: "10.19.1.213"
  - name: CACHE_REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: directus-redis
        key: password

# HPA
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Service DB
# https://docs.directus.io/self-hosted/config-options.html#database
# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
postgresql:
  enabled: true
  image:
    tag: "14.7.0"
  architecture: standalone
  primary:
    service:
      type: LoadBalancer
      loadBalancerIp: "10.19.1.212"
      loadBalancerSourceRanges:
        - "10.19.1.0/24"
    persistence:
      storageClass: longhorn-fast
      size: 8Gi
  auth:
    database: directus
    username: directus
    existingSecret: "directus-postgresql"

# Service Cache
# https://docs.directus.io/self-hosted/config-options.html#cache
# https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml
redis:
  enabled: true
  architecture: standalone
  image:
    tag: "6.2"
  master:
    service:
      type: LoadBalancer
      loadBalancerIp: "10.19.1.213"
      loadBalancerSourceRanges:
        - "10.19.1.0/24"
    persistence:
      enabled: true
      storageClass: longhorn-fast
      size: 8Gi
  auth:
    enabled: true
    existingSecret: "directus-redis"
    existingSecretPasswordKey: "password"
