apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-pool
  namespace: metallb-system
spec:
  addresses:
  {{- range $IPrange := .Values.reservedIps }}
  - {{ $IPrange }}
  {{- end }}
