# https://github.com/MoJo2600/pihole-kubernetes/blob/master/charts/pihole/values.yaml
pihole:
  persistentVolumeClaim:
    enabled: true
    existingClaim: "pihole-pvc"
  virtualHost: pihole.kolv.in
  serviceWeb:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: pihole-svc
      metallb.universe.tf/load-balancer-ips: "10.19.1.211"
  serviceDns:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: pihole-svc
      metallb.universe.tf/load-balancer-ips: "10.19.1.211"
  serviceDhcp:
    enabled: false
  admin:
    existingSecret: "pihole-secret"
    passwordKey: "password"
  extraEnvVars:
    TZ: UTC
  dnsmasq:
    customDnsEntries:
      - address=/pleiades.kolv.in/10.19.1.210
      - address=/pihole.kolv.in/10.19.1.211
