apiVersion: v2
name: metallb
description: A Helm chart for installed metallb
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: metallb
  version: 0.13.9
  repository: https://metallb.github.io/metallb
