# Default values for cloudflared.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

config:
  tunnel: my-tunnel
  tunnelCredsExistingSecret: tunnel-credentials
  credentialFilePath: /etc/cloudflared/creds/credentials.json
  disableAutoUpdate: true
  ingress: # https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
   - hostname: cms.kolv.in
     serviceName: directus
     servicePort: 8055
  metrics:
    updateFrequency: 3s
    servicePort: 2000

image:
  repository: cloudflare/cloudflared
  pullPolicy: IfNotPresent
  tag: "2023.3.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 100

podAnnotations: {}
podSecurityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
securityContext: {}
